spring.application.name=onlinelearning
spring.data.mongodb.uri=mongodb+srv://bolro:4848@onlinelearning.ywapodi.mongodb.net/onlinelearning?retryWrites=true&w=majority&appName=onlinelearning
server.port=8080